sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - stable
before_install:
  - npm i npm@^4 -g
install:
  - npm install
  - npm install -g cordova ionic
script:
  - ./build.sh
notifications:
  email: false
